// app
export const APP_EXIT = 'APP_EXIT';
// patient
export const PA_NEW_PATIENT_INFO = 'PA_NEW_PATIENT_INFO';

export const PA_GET_PATIENT_LIST = 'PA_GET_PATIENT_LIST';

export const PA_SAVE_PATIENT_INFO = 'PA_SAVE_PATIENT_INFO';
export const PA_DEL_PATIENT_INFO = 'PA_DEL_PATIENT_INFO';

export const PA_EDIT_SEL_PATIENT_BASE = 'PA_EDIT_SEL_PATIENT_BASE';
export const PA_EDIT_SEL_PATIENT_OUT_PATIENT = 'PA_EDIT_SEL_PATIENT_OUT_PATIENT';
export const PA_EDIT_SEL_PATIENT_COLPOSCOPY = 'PA_EDIT_SEL_PATIENT_COLPOSCOPY';
export const PA_EDIT_SEL_PATIENT_TREAT = 'PA_EDIT_SEL_PATIENT_TREAT';


export const PA_EDIT_SEL_PATIENT_ADD_RECORD = 'PA_EDIT_SEL_PATIENT_ADD_RECORD';
export const PA_EDIT_SEL_PATIENT_DEL_RECORD = 'PA_EDIT_SEL_PATIENT_DEL_RECORD';
