// app
export const APP_EXIT = 'APP_EXIT';
// patient
export const PA_SEARCH_PATIENT = 'PA_SEARCH_PATIENT';
export const PA_NEW_PATIENT_INFO = 'PA_NEW_PATIENT_INFO';
export const PA_SEL_PATIENT_INFO = 'PA_SEL_PATIENT_INFO';
export const PA_DELETE_PATIENT_INFO = 'PA_DELETE_PATIENT_INFO';

export const PA_GET_PATIENT_LIST = 'PA_GET_PATIENT_LIST';

export const PA_SEL_PATIENT_SAVE = 'PA_SEL_PATIENT_SAVE';
export const PA_SEL_PATIENT_DEL = 'PA_SEL_PATIENT_DEL';

export const PA_SEL_PATIENT_EDIT_BASE = 'PA_SEL_PATIENT_EDIT_BASE';


export const PA_SEL_PATIENT_ADD_RECORD = 'PA_SEL_PATIENT_ADD_RECORD';
export const PA_SEL_PATIENT_DEL_RECORD = 'PA_SEL_PATIENT_DEL_RECORD';

export const PA_SEL_PATIENT_EDIT_TREAT_RECORD = 'PA_SEL_PATIENT_EDIT_TREAT_RECORD';
export const PA_SEL_PATIENT_EDIT_COLPOSCOPY = 'PA_SEL_PATIENT_EDIT_COLPOSCOPY';
export const PA_SEL_PATIENT_EDIT_TREAT = 'PA_SEL_PATIENT_EDIT_TREAT';