// app
export const APP_EXIT = 'APP_EXIT';
// patient
export const PA_NEW_PATIENT_INFO = 'PA_NEW_PATIENT_INFO';

export const PA_GET_PATIENT_LIST = 'PA_GET_PATIENT_LIST';

export const PA_SAVE_PATIENT_INFO = 'PA_SAVE_PATIENT_INFO';

export const PA_EDIT_SEL_PATIENT_BASE = 'PA_EDIT_SEL_PATIENT_BASE';